name: Build APK

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Make Gradle executable
      run: chmod +x gradlew
    
    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace
    
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: APK-Debug
        path: app/build/outputs/apk/debug/app-debug.apk
